language: cpp

services:
  - docker

env:
    - BUILD_VARIANT=debug
    - BUILD_VARIANT=release
    - QBS_VERSION=qbs:1.4.2.Qt5.6.1
    - QBS_VERSION=qbs:1.4.2.Qt5.7.0
    - QBS_VERSION=qbs:1.5.0.Qt5.6.1
    - QBS_VERSION=qbs:1.5.0.Qt5.7.0
    - QBS_VERSION=qbs:1.5.1.Qt5.6.1
    - QBS_VERSION=qbs:1.5.1.Qt5.7.0

addons:
  apt:
    packages:
      - p7zip-full
      - tree

before_script:
  - export APP_DIR_NAME=simpleQtQmlApp
  - export APP_NAME=qtQmlsimple
  - export SRC_DIR=${TRAVIS_BUILD_DIR}
  - export INSTALL_DIR=/tmp/examples
  - export SCRIPTS_DIR=${SRC_DIR}/scripts

script:
  - ${SCRIPTS_DIR}/build_in_docker.sh
  - tree -L 5 ${INSTALL_DIR}
