os: Visual Studio 2015
version: 1.0.{build}

environment:
  PYTHON: "C:\\Python34"
  INSTALL_DIR: "%APPVEYOR_BUILD_FOLDER%\\install"
  ADDITIONAL_PARAMS: "qbs.installRoot:%INSTALL_DIR%"

  matrix:
  - BUILD_VARIANT: debug
    QTDIR: C:\Qt\5.8\msvc2015_64

  - BUILD_VARIANT: release
    QTDIR: C:\Qt\5.8\msvc2015_64

  - BUILD_VARIANT: debug
    QTDIR: C:\Qt\5.9\msvc2015_64

  - BUILD_VARIANT: release
    QTDIR: C:\Qt\5.9\msvc2015_64

install:
  - cmd: dir C:\Qt\
  - cmd: dir C:\Qt\5.8
  - cmd: git submodule update --init --recursive
  - cmd: curl -fsSL -o rclone.zip https://downloads.rclone.org/rclone-current-windows-amd64.zip && 7z e rclone.zip
  - cmd: curl -fsSL -o qbs.zip https://download.qt.io/official_releases/qbs/1.10.0/qbs-windows-x86_64-1.10.0.zip && 7z x qbs.zip
  - cmd: set PATH=%cd%\qbs-windows-x86_64-1.10.0\bin;%PYTHON%;%PYTHON%\Scripts;%QTDIR%\bin;C:\Qt\Tools\QtCreator\bin;%PATH%;%cd%
  - cmd: dir %cd%
  - cmd: set APP_DIR=%INSTALL_DIR%
  - cmd: set SCREENSHOTS_DIR=%INSTALL_DIR%
  - cmd: python -m pip install --upgrade pip && pip install --upgrade wheel -V && pip install --upgrade PySide easyprocess Pillow pyscreenshot pyvirtualdisplay -V
  - cmd: IF DEFINED INSTALL_MATPLOTLIB ( pip install --upgrade --pre https://pypi.python.org/packages/cp34/m/matplotlib/matplotlib-1.5.1-cp34-none-win32.whl -V )
  - python --version
  - pip --version
  - ps: $screen_resolution = '1280x800'; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
  - cmd: qbs --version

build_script:
- cmd: >-

    qbs setup-toolchains --detect

    qbs setup-qt %QTDIR%\bin\qmake.exe qt

    qbs config defaultProfile qt

    qbs --file %APPVEYOR_BUILD_FOLDER% --command-echo-mode command-line --clean-install-root %ADDITIONAL_PARAMS% %BUILD_VARIANT%

    dir %APPVEYOR_BUILD_FOLDER%

    dir %INSTALL_DIR%

    windeployqt --%BUILD_VARIANT% --no-system-d3d-compiler --no-translations --no-qmltooling --qmldir %APPVEYOR_BUILD_FOLDER%\examples\SimpleQtQmlApp\imports\Simple %APP_DIR%

# copy deployed files to needed locations (will be fixed in the future)
- cmd: >-

    cd %APP_DIR%

    dir

    FOR %%G IN ( iconengines imageformats platforms platforminputcontexts scenegraph ) DO ( IF EXIST %%G ( rclone copy %%G data\plugins\%%G\ && rmdir %%G /s /q  && echo "Copied and removed: %%G" ) )

    FOR %%G IN ( Qt QtGraphicalEffects QtQml QtQuick QtQuick.2 Qt3D ) DO ( IF EXIST %%G ( rclone copy %%G data\qml\%%G && rmdir %%G /s /q && echo "Copied and removed: %%G" ) )

    dir

    dir data\qml\

    python -u %APPVEYOR_BUILD_FOLDER%\\scripts\\take_screenshot.py -f %INSTALL_DIR%\\qtQmlsimple.exe -t 55 -o %SCREENSHOTS_DIR%\\screenshot.png

artifacts:
- path: install
  name: simpleQtQmlApp
